### ISSUE TITLE
Does not build against boost 1.60

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree-umbrella#108]
i can not compile webthree-umbrella release 1.0.1 against boost version 1.60, here are the logs https://gist.github.com/5chdn/37e7a66845e2417ed109

i'm on archlinux kernel 4.2.5-1-ARCH x86_64 GNU/Linux. webthree-umbrella release 1.0.0 was working fine with boost 1.58, and boost 1.59 only worked with following patches: #78 

please check the logs and let me know if you need more details.

**Comment by 5chdn** [comment]
using boost really sucks, every minor update breaks the builds.

as soon as this is fixed there will probably be 1.61 out with new issues ...

**Comment by bobsummerwill** [comment]
@oed @Jheguy2 @LefterisJP @chriseth @winsvega.

Hey guys!    Please could somebody attempt to characterize the root-cause of why newer Boost versions are often breaking?    I've seen tickets raised in a number of different places.

Is there a single root cause?    Or are the Boost developers just a bit crap when it comes to ensuring backwards compatibility?    Are we commonly seeing these breaks across multiple platforms for new boost releases?    Thanks!

**Comment by LefterisJP** [comment]
@bobsummerwill you can take a lok at the log and figure out quite easily. Boost devs have nothing to do with this.

And [I fixed](https://github.com/ethereum/libethereum/pull/143) this issue quite some time ago. It's just that nobody has updated the umbrella project in a while.

**Comment by LefterisJP** [comment]
I updated it now.

**Comment by bobsummerwill** [comment]
Thanks for the update, @LefterisJP.

**Comment by 5chdn** [comment]
Thanks.
