### ISSUE TITLE
Unify WIN32 checks

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#129]
At several points in the source we use different variations of
`#if WIN32`
`#ifdef _WIN32`
`#if defined(_WIN32)`

It seems that the version with underscore is the correct one and in general I prefer `#if defined(_WIN32)`.

**Comment by ramvi** [comment]
And `#ifndef WIN32`

**Comment by LefterisJP** [comment]
@ramvi that's just a negation of  `#if defined(WIN32)`

Yes the version with the underscore is the only correct one. Anything else should go away. Funny it was working so far :)

**Comment by bobsummerwill** [comment]
Yes - `#if defined(_WIN32)` is the correct expression, I believe.

WRT other expressions "working", that is usually by fluke because of hacks in various header files, or build files which just define multiple of these for the exact same reason as we have the ambiguity here.    Uncertainty about what the "right thing".    So "Fuck it, we'll just do them all!"

**Comment by ramvi** [comment]
Issue continued at #131

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/webthree/issues/99

**Comment by winsvega** [comment]
https://github.com/ethereum/libethereum/pull/173
https://github.com/ethereum/libweb3core/pull/53
https://github.com/ethereum/mix/pull/246
https://github.com/ethereum/webthree/pull/116
https://github.com/ethereum/webthree-helpers/pull/91
