### ISSUE TITLE
Move OverlayDB.cpp/.h from libdevcrypto to libdevcore

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#146]
Should only be a file move (and necessary changes in include statements).

**Comment by fossilet** [comment]
I would like to try this.

**Comment by chriseth** [comment]
@fossilet that's great, thanks! Please do, and come to https://gitter.im/ethereum/cpp-ethereum if you have any questions.

**Comment by fossilet** [comment]
@chriseth I have made changes in my forks of the submodules at fossilet/libweb3core@e800a21 and fossilet/libethereum@72ac151, but I have not figured out how to create a pull request for all these three repositories.

**Comment by bobsummerwill** [comment]
Hey, @fossilet!
So my understanding is that you will need to create pull requests for each individually.

There is some voodoo magic described here - https://github.com/ethereum/webthree-umbrella/wiki/Continuous-Integration - with which you can specify "build other repository with specific version" by adding comments in a certain format.     I think that you will need that for the pull request on libethereum to build correctly, because that will need your version of libweb3core, won't it?

Updates of the sub-modules of webthree-umbrella don't HAVE to happen at the same time.

**Comment by chriseth** [comment]
Thanks, @fossilet !
