### ISSUE TITLE
Script for fetching dependencies and building

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#165]
Taylor has done some preliminary work: https://gist.github.com/tgerring/1dd0c51adf3ab0387b3c
perhaps we could use `lsb_release -c` to avoid the complicated if structure
this could be tested using docker

**Comment by bobsummerwill** [comment]
Is there a specific use-case in mind for this script?

**Comment by chriseth** [comment]
The use-case is to simplify the build instructions to running a single script.

**Comment by bobsummerwill** [comment]
For end-users?  Or automation?   Or both?

**Comment by chriseth** [comment]
Both

**Comment by bobsummerwill** [comment]
See https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh which is coming live as part of the reorg, @tgerring.

Funny, when this issue was created in February, I didn't fully understand the use-case and forgot this issue was even present, and then I reinvented it.    Anyway - much broader range of distros supported and working through the rest.    See https://github.com/ethereum/webthree-umbrella/issues/639.

So I'll close this old issue off.
