### ISSUE TITLE
Where is the Jenkins project in Github?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#211]
Hey Lefteris!

So I have the repos which I forked from YOU of the cleaned up copies of the Jenkins setup.

```
https://github.com/LefterisJP/eth-jenkins-config and https://github.com/arkpar/docker.
```

Is that first one just a snapshot of the running Jenkins instance?   As in, the actual DB on the machine is "the truth", right?    And I should be able to get direct access to that now I am part of ETHDEV.   If so, I will do that.   Thanks!

**Comment by LefterisJP** [comment]
Hey Bob,

So that's a snapshot I took of the time. Since then, there have been many changes, and I am sure it's not "the truth". Also it's just the configurations and not the history of the builds, which I guess you won't need. I would simply make a snapshot of the current jenkins instance (and not in github, just a tar file) and work from there.

**Comment by bobsummerwill** [comment]
Gotcha - makes sense!    Thanks :-)
