### ISSUE TITLE
Debian - Errors when preparing to build the project

### ISSUE THREAD

**Issue by gpkc** [ethereum/webthree-umbrella#246]
Hi,
I'm trying to build the project. I am issuing the following commands, on a Debian machine:

> git clone --recursive https://github.com/ethereum/webthree-umbrella
> cd webthree-umbrella/
> git checkout release
> mkdir build
> cd build/
> cmake .. -DETHASHCL=1 -DGUI=0 -DEVMJIT=0

Then I get this output, with errors:
https://gist.github.com/gpkc/f9b55b0a039784a7da4e

**Comment by bobsummerwill** [comment]
Hello there!
I'm afraid you are off on your own a little here.   We don't have Debian install instructions.

Maybe you could make a Wiki page for that and link it here?   https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Linux

If you just detail what you have done for you build steps there, and a big "THIS IS BROKEN" disclaimer on the top of it, perhaps we can iterate that from "broken" to "working".

Also - quick note - for logs, it is better to use http://gist.github.com and link to them.   Doesn't clutter up the bug, and the formatting doesn't got weird like the above, because it is assuming Markdown formatting.

Best wishes, @gpkc!

**Comment by gpkc** [comment]
Hmm, that's unfortunate.
I will try to put what I've done on a Wiki page as you said.
The problem is that many of the dependencies didn't exist at all on the debian package management system. But I was able to build and install them successfully.
I actually believe that there are many path problems on some of the eth packages. For example, take one of the errors:

```
CMake Error at libethereum/test/CMakeLists.txt:30 (file):
file STRINGS file
"/home/padmec/Programas/webthree-umbrella/libethereum/test/./..//./fuzzHelper.cpp"
cannot be read.
```

Resolving this path would take us to

> "/home/padmec/Programas/webthree-umbrella/libethereum/fuzzHelper.cpp"

Which really doesn't exist. The correct path would be:

> "/home/padmec/Programas/webthree-umbrella/libethereum/test/fuzzTesting/fuzzHelper.cpp"

I'm not sure where in the build process, the builder is freaking out and breaking the paths.

**Comment by bobsummerwill** [comment]
Right.    How up-to-date is your CMake?

**Comment by gpkc** [comment]
Version 3.0.2. You think that might be the problem? I will try to compile a newer version, as this is the one available on the package manager.

**Comment by gpkc** [comment]
Nevermind, updating CMake worked. After it, I was able to generate the Makefile and compile successfully.
Thanks.

**Comment by bobsummerwill** [comment]
Brilliant!   That was easy :-)
Have fun.
