### ISSUE TITLE
Blockchain Sync crash on Morden

### ISSUE THREAD

**Issue by yann300** [ethereum/webthree-umbrella#321]
./eth --morden

assertion failure in BlockChainSync.cpp:107 coming from BlockChainSync.cpp:481

probable cause: since we currently have two chains in morden, sync is more complicated which leads to elements being deleted, which did not happen before.

**Comment by bobsummerwill** [comment]
Getting a bunch of the following for an `eth --morden`.   What do these mean?

  Disconnect (reason: Subprotocol reason.[0m )
[93m⧎[97m ◌  [35m11:43:54.332[0m[30m|[34mp2p[0m[30m|[36ma979fb57…[0m[30m|[36mGeth/v1.3.5-34b622a2/linux/go1.5.1[0m  Closing peer session :-(

Do they mean that we are finding peers and then throwing them away because they are not Homestead-compatible?

**Comment by bobsummerwill** [comment]
Two chains, because we're not fully through the Homestead switchover, and maybe don't have enough of the peers on Homestead-compatible clients yet?

**Comment by chriseth** [comment]
@bobsummerwill disconnects because genesis hash is different (you can see it in the line above - at least if you remove the escape symbols).

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/libethereum/pull/204
