### ISSUE TITLE
sources missing submodules

### ISSUE THREAD

**Issue by nerdralph** [ethereum/webthree-umbrella#343]
/ethereum/webthree-umbrella/archive/v1.2.1.zip (and .tgz) seem to be missing the submodules files.  alethzero, libethereum, etc are empty.

**Comment by bobsummerwill** [comment]
I assume you grabbed the ZIP from the release page?

That's why we have that warning:

Please do not use the source archive below, it misses important dependencies. If you want to build from source, follow the Building from source instructions and checkout the appropriate tag (v1.2.2) for webthree-umbrella.

Please head over to http://docs.ethereum.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/.

If you just want to grab the code to look at it then you'll just want to do a git clone -recursive.

Best wishes!

**Comment by bobsummerwill** [comment]
Hey @nerdralph,

Aside - @programonauta is working on a pull-request to give a useful error message for just this issue:

https://github.com/ethereum/webthree-umbrella/pull/346
