### ISSUE TITLE
ethminer 1.2.1 can't mine CPU and GPU on same machine

### ISSUE THREAD

**Issue by nerdralph** [ethereum/webthree-umbrella#344]
Platform Win7e/64.
mining in farm mode with openCL GPU works fine.  Trying to run another ethminer instance in CPU mode crashes.  cli example:
C:\Program Files\Ethereum>ethminer -C -F http://eth-us.dwarfpool.com/foo
miner  13:26:20.251|main  Getting work package...
  X  13:26:20.336|main  Failed to submit hashrate.
  X  13:26:20.340|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : An error occurred

I tried to see if a single ethminer instance can mine both CPU and GPU (-C -G), but it only mines using the GPU.

**Comment by bobsummerwill** [comment]
Thanks for the report, @nerdralph!

Yeah, you don't want to running two ethminer instances at the same time.   We should really put a mutex or something on that, so you get a nice obvious error message :-)

Thanks again.

**Comment by smartbitcoin** [comment]
but it's obvious a network error msg,  the pool is not connect-able.

**Comment by bobsummerwill** [comment]
Hey @nerdralph,

I would recommend that you check out the https://github.com/Genoil/cpp-ethereum/ ethminer fork, which appears to be the leading solution.

Also check out the side-bar on http://reddit.com/r/etherminer for the guides there.

Good luck.  Please do let us know if you find a working setup and let us know what you did.   Thanks!

**Comment by 3esmit** [comment]
I'm in the same issue.
Why closed? This is fixed in new Genoli miner? 
When I try to open 2 instances windows give me that classic error close application message and try to report error to Microsoft.  I believe this happens because DAG file is in use by other instance, this makes any sense?

Now I'm farming in GPU using genoli's ethminer cudaminer fork and soloing in CPU (wish me luck, thanks) using geth, but I want to farm with both, as it 'seems' more profitable (i'm not feeling lucky :disappointed: ).
