### ISSUE TITLE
AlethOne stuck on Initialising miner...

### ISSUE THREAD

**Issue by moonmang** [ethereum/webthree-umbrella#369]
Blockchain is synced and when I click Start Mining I get this and it never changes:

![image](https://cloud.githubusercontent.com/assets/17795027/13869396/69af6008-ec91-11e5-90a8-4e7c74aa603f.png)

Is there a basic prerequisite I may have overlooked? Windows 8.1, R9 390 with latest drivers

**Comment by bobsummerwill** [comment]
Hey @moonmang,

AlethOne and AlethZero are slated for death (https://blog.ethereum.org/2016/02/12/ethereum-dev-update-c-roadmap/), and it increasingly looks like we need to put a bullet in their backs right now and remove that prominent link to "One Click Miner" on http://ethereum.org.     Sorry that you were a victim of their imminent demise.

I would recommend that you consider switching to ethminer+geth, which is what nearly all miners appear to be doing, and also to check out the https://github.com/Genoil/cpp-ethereum/ ethminer fork, which appears to be the leading solution.

Also check out the side-bar on http://reddit.com/r/etherminer for the guides there.

Good luck.  Please do let us know if you find a working setup and let us know what you did.   Thanks!

**Comment by moonmang** [comment]
I still don't understand any of this. The Github link you provided just
looks like a list of jargon and the reddit link is private. Is there any
mining guide available that's not out of date?

**Comment by bobsummerwill** [comment]
Sorry about that, @moonmang.    Let me try to be clearer.

AlethOne is being discontinued, so I'm afraid that if it isn't working for you already that you are out of luck, because we won't be fixing any issues.     The range of different GPU hardware and many other factors have meant that "One Click Miner" just isn't delivering that experience, as you have discovered yourself.    So we're dropping that effort.    Miners will need to use ethminer on the command-line.

Sorry, I had a typo on the Reddit link.   I meant http://reddit.com/r/ethermining.
