### ISSUE TITLE
Include MSVCR120.dll in windows installer

### ISSUE THREAD

**Issue by koeppelmann** [ethereum/webthree-umbrella#387]
Hey - I used this installer https://build.ethdev.com/cpp-binaries-data/release-1.2.2/Ethereum.exe and installed cpp-ethereum under windows 10. Installer completed successfully but when I want to start one of the 3 programs I get:
"The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem.

Reinstalling did not helped.

**Comment by bobsummerwill** [comment]
Thanks for the report, @koeppelmann!

Looks like you are missing "Visual C++ Redistributable Packages for Visual Studio 2013".   If you install this you should be up-and-running again:
https://www.microsoft.com/en-us/download/details.aspx?id=40784

I need to look at reports of missing DLLs in our Windows ZIP too, and will look at this at the same time.

That issue is https://github.com/ethereum/webthree-umbrella/issues/310

**Comment by chriseth** [comment]
Seems to be fixed. Please reopen if not.

**Comment by chriseth** [comment]
To clarify: This file is present in the file `win_eth.zip`, so it should also be present in the installer, that needs to be investigated.

**Comment by bobsummerwill** [comment]
RE: Your comment above, @chriseth.   OK - will do.

**Comment by bobsummerwill** [comment]
Just re-tested on a fresh Windows Server VM on Azure, and there are still issues.

Launching AlethZero gives a "MSVCP120.dll is missing" error, which is classic.     It looks the install installs a vc dist EXE, but doesn't actually RUN IT as part of the installation step.

The ZIP (https://builds.ethereum.org/cpp-binaries-data/release-1.2.4/win_eth.zip) has these DLLs just dropped in there, which doesn't seem right either:
- msvcp120.dll
- msvcr120.dll
- vccorlib120.dll

I **think** those should be installed system-wide, shouldn't they?   Or maybe not.

**Comment by bobsummerwill** [comment]
So just having the two msvc\* DLLs dropped in that directory appears to be enough for AlethZero and Mix to run, so there might be a quick-and-nasty fix here if chaining the installer proves too hard.

Look like vccorlib120.dll is the WinRT support, which I would be very surprised if we needed.   That might well have been added to the ZIP as part of a batch of DLLs to try to get it to work?

**Comment by bobsummerwill** [comment]
OK - Windows ZIP-ping happens in a magic script inside Jenkins:

http://52.28.164.97/configfiles/show?id=org.jenkinsci.plugins.managedscripts.PowerShellConfig1444842304838

.... and that just batch copies all DLLs in C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x64\Microsoft.VC120.CRT\ into the output directory (which is why all 3 are there, not just the ones for unmanaged apps).

See also https://www.softwariness.com/articles/visual-cpp-runtime-libraries/ for more information on how these runtime libraries work.    It seems that simply copying the DLLs **is** just fine.

**Comment by bobsummerwill** [comment]
See also https://msdn.microsoft.com/en-us/library/8kche8ah.aspx.

So **msvcr120.dll** is the C runtime.    **msvcp120.dll** is the C++ runtime.

**Comment by bobsummerwill** [comment]
See also https://braintrekking.wordpress.com/2013/04/27/dll-hell-how-to-include-microsoft-redistributable-runtime-libraries-in-your-cmakecpack-project/.

**Comment by chriseth** [comment]
@bobsummerwill so what is still to be done here?

**Comment by bobsummerwill** [comment]
Well - I spent all of yesterday working to "grok" this, and I still don't have an easy solution.

So what I am going to do is close the issue, and update our Release pages on GitHub to say "please run the vcredist.exe installer".     Because it isn't worth spending any more time on.

The ZIP works.    The installer needs **some magic tweak** done on it to chain the installer.    What that is evades me, and is seriously time-consuming to try to understand.

But do we even really need a Windows installer?    When we decouple all the packages they might be better as standalone self-contained ZIPs anyway?
