### ISSUE TITLE
error: suggest explicit braces to avoid ambiguous ‘else’ 

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree-umbrella#537]
latest release 1.2.5 fails with:

```
[ 10%] Automatic moc and uic for target mix-ide
[ 10%] Built target ethash-cl
[ 10%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 10%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o
[ 11%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/CommonJS.cpp.o
[ 11%] Built target mix-ide_automoc
[ 11%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/MemoryDB.cpp.o
/home/afri/Sync/AUR/ethereum/src/ethereum/libweb3core/libdevcore/TransientDirectory.cpp: In destructor ‘dev::TransientDirectory::~TransientDirectory()’:
/home/afri/Sync/AUR/ethereum/src/ethereum/libweb3core/libdevcore/TransientDirectory.cpp:62:5: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=parentheses]
  if (!ec)
     ^
[ 11%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
cc1plus: all warnings being treated as errors
libweb3core/libdevcore/CMakeFiles/devcore.dir/build.make:62: recipe for target 'libweb3core/libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o' failed
make[2]: *** [libweb3core/libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:325: recipe for target 'libweb3core/libdevcore/CMakeFiles/devcore.dir/all' failed
make[1]: *** [libweb3core/libdevcore/CMakeFiles/devcore.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Is this also a GCC 6 problem?

```
0 ✓ user@host ~ $ uname -a
Linux x230 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux
0 ✓ user@host ~ $ gcc --version
gcc (GCC) 6.1.1 20160501
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bobsummerwill** [comment]
Hey there!

It might be GCC 6.1 related, but I have seen this warning on other platforms too.    I think it's related to the way in which `clog()` is defined.     Please could you see whether adding braces around that `if` resolves it?    If so, just make a PR and I will merge that right away.

We didn't announce `v1.2.5` because there are still unresolved Windows issues.    We will be doing a `v1.2.6` in the next few hours, so maybe you just skip packaging v1.2.5?    If this is a quick fix, maybe we can even slip your PR into v1.2.6?

**Comment by chriseth** [comment]
@5chdn can you try if this is fixed in latest develop?

**Comment by bobsummerwill** [comment]
Did you make any change for it, @chriseth?

As I said above, I have seen that warning in other places too - maybe cross-builds?

**Comment by bobsummerwill** [comment]
I see that you had made a PR, @chriseth.    I just merged than, and it auto-closed this issue, so I just reopened it.

Yes, please do try `develop`, @5chdn :-)

**Comment by ijcoe6ru** [comment]
The bug will appear if cmake is run with `-DCMAKE_BUILD_TYPE=Release`.

**Comment by bobsummerwill** [comment]
Right - even with these braces added, eh?

Is the behavior difference before-and-after this commit from @chriseth?    Like was in both configs, now only in Release?

I think not, eh?    Because I seem to remember that the ambiguous else is actually within the macro itself, isn't it?   I remember trying to add more braces within the macro definition for clog, and not getting very far with that, but that is probably what really needs to happen here.

Or better yet, for us just to remove those horrible macros entirely and replace them with something a lot more rational and simple.    Operator overloads within macros is a nasty combination.   What is worse, it means that you cannot actually completely eliminate the code anyway.    If you look into this code, you end up with a "null object" in release.

**Comment by ijcoe6ru** [comment]
The bug will appear in Release because another macros are defined in the if-else way only if `NDEBUG` is true. My commit fixed the bug by changing the macros. In my commit, the macros don't contain if-else, so adding braces will not be necessary.

There are multiple places in the code that will produce the warning. The commit from @chriseth fixed one of them.

**Comment by bobsummerwill** [comment]
Great, @ijcoe6ru :-)
Thanks for that!

**Comment by 5chdn** [comment]
develop builds now. thanks.
