### ISSUE TITLE
Linux - Change to build instructions required around LLVM?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#549]
See https://gitter.im/ethereum/mix?at=574ff802454cb2be0951446f.

@chfast says "LLVM hosting for dep packages has been shut down."

So we're going to need to update our build instructions, eh?    What do we need to do instead?

**Comment by chfast** [comment]
I think for external users we should disable the EVMJIT by default. There are always some issues with build with it.

Options:
1. Just put instructions in the docs (for all systems).
2. Disable EVMJIT in cmake by default (this is ok provided core developers will remember to build with it from time to time).
3. Improve cmake bundles and make them part of the docs -- most complains is from users wanting to have solidity and IDE. They don't need EVMJIT at all.

**Comment by bobsummerwill** [comment]
When we have "standalone solidity", this will certainly be much easier, but we need a solution in the short-time.

We could certainly just "turn off" `EVMJIT`, but that is really weak.    Even if we turn it off by default, we still need instructions on how to turn it back on again.    So, my question for right now is "What do we need to do on Ubuntu instead of what were previously doing which has just been broken underneath us?"     Do you have any URLs or posts you could share on exactly what has changed here, @chfast?

Our written instructions will be 100% equivalent to the https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/setup.sh and https://github.com/bobsummerwill/solidity/blob/solidity_standalone/setup.sh scripts which I've been working on (though I can't remember why that solidity one has LLVM in it - I was probably screwing around with something on CircleCI, which I have since abandoned because of caching issues which were exceedingly annoying).

What do you mean by "CMake bundles"?    I'm afraid I don't quite know what you mean there.

**Comment by chfast** [comment]
LLVM switched off APT repo because it generates a lot of traffic. They are searching for an alternative solution. https://groups.google.com/forum/#!topic/llvm-dev/wOoTO9fD4nw

Simplest option is to build with `cmake -DEVMJIT=OFF`. We can put that in docs.

Bundles is our feature of cmake -- just flag set. E.g. `cmake -DBUNDLE=solidity` to configure only targets related to solidity. I think this is too fragile. I prefer configuring all targets and build only the ones I currently need.

**Comment by bobsummerwill** [comment]
OK ... I've done `-DEVMJIT=0` for my Appveyor and TravisCI automations in my repo reorg branches, and we'll see how that goes.    Should improve the turnaround times, for sure :-)

So I suppose we would have to add LLVM 3.8 to our own PPAs to "fix this" ?

I don't think we'll need bundles.    The new repos will be 1-1 on what people need/want.

**Comment by bobsummerwill** [comment]
- https://ci.appveyor.com/project/bobsummerwill/cpp-ethereum/build/1.0.104
- https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/135144907

**Comment by chfast** [comment]
I've seen that Ubuntu 16.04 have LLVM 3.6 and LLVM 3.8.
1. I would need to check if the package llvm-3.8-dev from Ubuntu 16.04 works as expected.
2. If 1. is fine, we could backport it to our PPA.
3. Ultimately, I'm thinking about pulling and building LLVM directly with EVMJIT's cmake script.

Can you update the docs in the way you think will be suitable for current situation?

**Comment by bobsummerwill** [comment]
Perhaps instead of (3) you actually just add LLVM as a sub-repo under evmjit?

https://github.com/llvm-mirror/llvm/tree/release_38

**Comment by bobsummerwill** [comment]
The idea of adding more-and-more of our external dependencies as git sub-modules really is hugely appealing to me, because it gives us 100% control of our versioning and build process, where use of external binaries will always be very problematic and "noisy" and work-generating.      The use of sub-modules also makes irrelevant the differences between package versions in different Linux distros (even within Ubuntu versions), rolling package managers on Arch and OS X, and NO package manager on Windows.

Instead, we just have exactly what we want and build it exactly how we want.

**Comment by chfast** [comment]
Git submodule would be a possible way of _pulling_ in (3). But we still need to build it.

**Comment by chriseth** [comment]
I would prefer having llvm taken just from another ppa. If we need to build LLVM ourselves, this would mean even more dependencies (i.e. the dependencies LLVM has).

**Comment by bobsummerwill** [comment]
Well, @chriseth, I hope that an outcome of the LLVM team taking their hosting offline will be a realization that lots of people need an LLVM PPA for Ubuntu :-)      Hopefully somebody can step up and we can just leech of them!

RE: "dependencies LLVM has" .... do you know if it drags further indirect dependencies in, @chfast?

**Comment by chfast** [comment]
@chriseth LLVM has no external dependencies (almost, libedit-dev on Linux), it builds on everything:
- http://lab.llvm.org:8011/console
- http://lab.llvm.org:8080/green/

The true issues is we have too many sources of pre-built LLVM and we are not able to maintain them all. Some part of the problem is also that LLVM is distributed as static libraries and packaged differently depending on OS/maintainer.
- Debian packaging is unstable. Usually cmake files are broken. It can happen the package is broken on Ubuntu 14.04 but ok on Ubuntu 16.04. All alive versions of Debian/Ubuntu are supported (~6) but the issue can happen on any of them.
- Homebrew was broken for some time because they refused to packaged LLVM 3.7.0 because it contained bugs.
- We have reports it does not work on Fedora: https://github.com/ethereum/webthree-umbrella/issues/524
- How about all these systems: http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/portability.html#cpp-ethereum-portability ?

It does not seems to be feasible at the moment. I don't want to spend all my time on fixing LLVM packaging (I really fixed the Debian package for 3.7, but they managed to brake it again). It takes enormous amount of time.

**Comment by chfast** [comment]
@bobsummerwill Kinda right. We can see what Rust, LDC and others will do to fix that for Travis.

**Comment by chfast** [comment]
Actually, extensive usage of CI was the reason LLVM turned off the APT repo. It generated _almost 95% of I/O on llvm.org and more than 40% of network bandwidth alone_.

Sorry for the series of messages...

**Comment by bobsummerwill** [comment]
So this has actually been resolved, via @chfast's changes within evmjit.
