### ISSUE TITLE
Build breaks for Mac OS X 10.11.5 (target aleth)

### ISSUE THREAD

**Issue by ktorn** [ethereum/webthree-umbrella#562]
I'm encountering qt5 related build errors when building webthree-umbrella.

I've successfully installed all the [dependencies](http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/osx.html), including the rather lengthy `brew install qt5 --with-d-bus` step.

When running `make -j2` the build fails after some time, on target aleth, with some [errors](https://gist.github.com/ktorn/2d08fc19bae91dec36f19af9654801c3).

**Comment by bobsummerwill** [comment]
Hey @ktorn,

It looks like you probably have some other existing Qt install which is confusing things:

```
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/QObject:1:
In file included from /usr/local/opt/qt5/lib/QtCore.framework/Headers/qobject.h:48:
In file included from /usr/local/include/QtCore/qmetatype.h:49:
In file included from /usr/local/include/QtCore/qdatastream.h:46:
/usr/local/include/QtCore/qiodevice.h:68:14: error: base class has incomplete type
```

Because this sequence starts with the Homebrew Qt5 version (`/usr/local/opt/qt5`) but then ends up in some other version (`/usr/local/include`).

I've never had this issue myself but I remembering seeing some notes which other people had made about Qt5 not wanting to co-exist with earlier Qt installs.

There are both Qt and Qt5 formulas (https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb).    Could you check if you have `Qt` installed?   If so, I am afraid that you will need to remove that.

What are you trying to get built?   Mix?

**Comment by ktorn** [comment]
@bobsummerwill,

Yes, trying to build Mix.

You are right, an older version of Qt was installed and was conflicting.

A `brew uninstall --force qt` seems to have fixed it. Thanks!

**Comment by bobsummerwill** [comment]
Thanks for the feedback.

I've updated the OS X building from source instructions to add that detail, plus some other cleanup.

http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/osx.html

Please do build the Debug configuration of Mix, if you missed out on all the noise there?    Or maybe that is why you are building from source in the first place?

```
cmake -DCMAKE_BUILD_TYPE=Debug
```

See https://github.com/ethereum/webthree-umbrella/issues/546
