### ISSUE TITLE
[Nvidia] eth & ethminer don't work anymore after Cuda installation

### ISSUE THREAD

**Issue by slaivyn** [ethereum/webthree-umbrella#592]
```
# eth
^C^C^C

^Z^Z

^[^[^[
```

I can't get back the command line. The only thing I can do is closing the (remote) terminal.

Same behavior for "eth -M", "eth -M -G", "eth -h", "ethminer"...

Nothing in the standard logs.

```
# lspci | grep -i nvidia
02:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
02:00.1 Audio device: NVIDIA Corporation GM204 High Definition Audio Controller (rev a1)
05:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
05:00.1 Audio device: NVIDIA Corporation GM204 High Definition Audio Controller (rev a1)
```

geth, ethkey, ethtest and ethtool work (or at least print something).
geth is generating the DAC without any problem.

Any idea? Any thing I can do to investigate (no more idea on my side...)

Thank you!

**Comment by slaivyn** [comment]
```
W: Failed to fetch http://llvm.org/apt/trusty/dists/llvm-toolchain-trusty-3.7/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://llvm.org/apt/trusty/dists/llvm-toolchain-trusty-3.7/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead
```

Could this be related to my problem? I don't know exactly what llvm is but if the version used is not the one from this PPA maybe it could cause some issues.

At llvm.org/apt there is this message:

> APT mirror was temporary switched off due to excess load. We are working on bringing it back. Stay tuned!

**Comment by bobsummerwill** [comment]
Hey!

The LLVM build issue you are seeing is https://github.com/ethereum/webthree-umbrella/issues/549.

To workaround that, just build with `cmake .. -DEVMJIT=0` which turns off the JIT version of the Ethereum VM, which is the code which uses LLVM.

But that is just another issue which you are hitting, not the cause of your problem.

For your specific mining issue, I would suggest that you contact the mining community for help:
- https://gitter.im/ethereum/minercommunitysupport
- https://reddit.com/r/ethermining
- https://ethereum.stackexchange.com/?tags=mining

There is lots of voodoo and tribal knowledge in mining, because of the huge variety of hardware and drivers.

Also, do try http://github.com/Genoil/cpp-ethereum which is better maintained that the official miner.   See #313 and #315.

**Comment by slaivyn** [comment]
Problem fixed! It was entirely related to nvidia drivers installation...

Thank you for your help!!

**Comment by bobsummerwill** [comment]
Excellent, @slaivyn.   I am very glad to hear it.

Best wishes!
