### ISSUE TITLE
Where Is AlethOne? 

### ISSUE THREAD

**Issue by AaronD1** [ethereum/webthree-umbrella#681]
I've seen AlethOne in images, videos, and the documentation for mining Ethereum. I've also seen post saying that "AlethZero" will be killed soon, but what about AlethOne? I've been having a lot of trouble mining (My GPU isn't submitting shares to the pool) on ethminer and I just want something simple. Why is AlethOne suddenly gone?

**Comment by bobsummerwill** [comment]
AlethOne was retired several months further back.

One-click mining turned out to be a mirage.   There is a giant raft of "tweakiness" at the driver level, and wrapping a GUI around it doesn't help at all.

It is possible that some GUI wrapper for mining might make sense as a Mist plugin in the future, but mining is a common-line activity right now.

It's probably best for anybody who is mining to use @Genoil's https://github.com/Genoil/cpp-ethereum ethminer variant for the time being, because it has had the most love.

See https://github.com/ethereum/webthree-umbrella#313 and https://github.com/ethereum/webthree-umbrella#315.

There is a gitter channel where many miners hang out at https://gitter.im/ethereum/minercommunitysupport and those guys have the best chance of helping you.

Best wishes!
