### ISSUE TITLE
Missing dependency to MSVCR120.DLL under Win7 non-dev PC.

### ISSUE THREAD

**Issue by imifos** [ethereum/webthree-umbrella#76]
When installing version 1.0 Release Candidate 2, 13 Sep 2015, on a non-development Windows 7 PC, there is a dependency to MSVCR120.dll missing. MSVCR120.dll, the Visual C++ 2013 Runtime, should be included in the distribution.

As work around, it can be downloaded here:

Visual C++ Redistributable Packages for Visual Studio 2013
http://www.microsoft.com/en-US/download/details.aspx?id=40784

**Comment by LefterisJP** [comment]
Hello, what exactly did you install and how in order to not get the MSVC redistributable?

**Comment by imifos** [comment]
I just downloaded this
https://github.com/ethereum/webthree-umbrella/releases/tag/1.0rc2

Installed it on a non-dev PC and wasn't able to start till I downloaded the VC RT from MS.

**Comment by bobsummerwill** [comment]
Hey @imifos!  Since this ticket was logged, 1.0.0 and 1.0.1 installers were released.

@LefterisJP Do you know/remember if anything was modified in the Windows installer setup after this issue was logged?   I know that Windows installers DO often need this kind of stuff explicitly hooked into them.   VC redistributables.   DirectX runtime, etc.    And that developers often miss that need in testing because they aren't "clean" machines.    And @caktux.

**Comment by bobsummerwill** [comment]
Old report of the same issue now tracked as https://github.com/ethereum/webthree-umbrella/issues/387.
