### ISSUE TITLE
Please can we have a read-only public view onto Jenkins?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#85]
As discussed on Gitter a while back, please can we have a read-only public view onto Jenkins?

I want to replicate this environment to cover our cross-builds.

It will also be useful to see when there are build breaks in the native builds.   Thanks!

**Comment by LefterisJP** [comment]
We can provide, public view to anonymous github users (our Jenkins use Github OAUTH) so that you can see the job results. As for the configuration there are some small things that need ironing out if we are to also show it to the public.

I can talk to you privately in Gitter in the meantime to explain what we do since I am the one who built the CI system during the last 2 months.

Bear in mind though that it is always a work in progress.

**Comment by bobsummerwill** [comment]
Thanks for the update, and for the private gitter messages!

**Comment by bobsummerwill** [comment]
Delivered by @LefterisJP :-)

It is at  http://52.28.164.97/.
